# Generated by Django 5.0.1 on 2024-11-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('program_or_services', models.CharField(max_length=255)),
                ('insurance_company', models.CharField(max_length=255)),
                ('insurance_number', models.CharField(max_length=100)),
                ('preferred_language', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('guardian_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('referred_by', models.CharField(max_length=100)),
                ('date_of_referral', models.DateField()),
                ('referral_phone', models.CharField(max_length=20)),
                ('referral_from', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
