# Generated by Django 5.0.1 on 2024-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_compliancemessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('program_or_services', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='referrals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='compliancemessage',
            options={'permissions': [('view_compliance_message', 'Can view compliance forms')], 'verbose_name': 'Compliance Form', 'verbose_name_plural': 'Compliance Forms'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'permissions': [('view_contact_message', 'Can view contact forms')], 'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
    ]
