# Generated by Django 5.0.1 on 2024-11-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_referral_alter_compliancemessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'permissions': [], 'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
    ]
