# Generated by Django 5.0.1 on 2024-11-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'permissions': [('can_view_subscribers', 'Can view subscribers')]},
        ),
    ]
