# Generated by Django 5.0.1 on 2024-12-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_boardmember_centrostaff_alter_donor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(default='vremos04', max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('read_time', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('external_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
