# Generated by Django 5.0.1 on 2025-06-03 18:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_newsarticle_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
