# Generated by Django 5.0.1 on 2025-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='featured_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
