# Generated by Django 5.0.1 on 2025-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_communitysupportcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySupportHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Worcester (Central)', max_length=100)),
                ('days', models.CharField(default='Monday – Friday', max_length=100)),
                ('time', models.CharField(default='9:00 AM – 5:00 PM', max_length=100)),
            ],
        ),
    ]
