# Generated by Django 5.0.1 on 2025-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_familysupporthours'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Worcester', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
