# Generated by Django 5.0.1 on 2025-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_childrenservicescontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NACDCBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NACDCContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('link_1_text', models.CharField(blank=True, max_length=255)),
                ('link_1_url', models.URLField(blank=True)),
                ('link_2_text', models.CharField(blank=True, max_length=255)),
                ('link_2_url', models.URLField(blank=True)),
            ],
        ),
    ]
