# Generated by Django 5.0.1 on 2025-06-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rebuildingtestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILACImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ilac_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
