# Generated by Django 5.0.1 on 2025-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_ilacimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionBoxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('Complaint', 'Complaint'), ('Suggestion', 'Suggestion'), ('Survey', 'Survey')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suggestion Box Submission',
                'verbose_name_plural': 'Suggestion Box Submissions',
            },
        ),
    ]
